name: Collaborative workflow

on:
  push:
    branches: 
      - main

jobs: 
  update_html_and_readme:
    runs-on: ubuntu_latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Insert Update Message into Index.html 👈 New Step
        run: |
          # The sed command needs to be here, under 'run:'
          # Note: We use the single-quote syntax to make sure the full date string is preserved
          sed -i '/<\/body>/i <p>Updated by Team Leader on '"$(date)"'</p>' index.html
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Workflow: Updated HTML and README for ${{ github.actor }}" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
